# Generated by Django 5.2.10 on 2026-03-05 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_productmapping_mrp'),
        ('user', '0003_usersettings_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='companies.tallycompany'),
        ),
    ]
