# Generated by Django 5.2.10 on 2026-03-05 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_productmapping_mrp'),
        ('user', '0005_alter_usersettings_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usersettings',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_settings'),
        ),
    ]
