# Generated by Django 5.2.10 on 2026-01-25 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tally Companies',
                'unique_together': {('user', 'company_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_description', models.TextField()),
                ('tally_item_name', models.CharField(max_length=255)),
                ('last_sales_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mappings', to='companies.tallycompany')),
            ],
            options={
                'unique_together': {('company', 'json_description')},
            },
        ),
    ]
