# Generated by Django 5.2.10 on 2026-02-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmapping',
            name='alt_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
