# Generated by Django 5.2.10 on 2026-02-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_productmapping_alt_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmapping',
            name='mrp',
        ),
    ]
